### PR TITLE
FIX: Oxigen 'Launch' button

### PR DESCRIPTION
**Pull request by jbr1989**

### CODE REVIEW

**Comment by jbr1989** [comment]
Did you overwrite the FIX?

**Comment by jbr1989** [comment]
Only change 'reply-markup-button-text' for 'reply-markup-button' and work it !!!

**Comment by thebrumby** [comment]
Hi, 

Yes, I overwrote the "fix". When creating a new account the "Launch" pop-up still appears, by removing it, it wasn't able to complete the setup process. 

But thanks for the commits, I'll take a look at the others over the next 24-hours :)

**Comment by jbr1989** [comment]
I don't know in new account, but in my existing account not appear "Launch" pop-up.
And script can't enter to iframe game.

**Comment by thebrumby** [comment]
Hi,

For us, The script enters the iframe, but the content is blocked by the game developer if using VPS (since they implemented Cloudflare).  However if you run the script from your home network, it still works. 

If you have it working with your step, maybe we need to add it as an extra step after “Launch”? While I haven’t looked at Oxygen for a while, but interested if you have it working on VPS 👍🏼

**Comment by jbr1989** [comment]
03-timeout-finding-button

It appears this for me.
I'm working on VPS. If it apply my 'fix', it work fine.

Launch button never appeared for me, only "Play Now!" button

**Pull request merged**
