### PR TITLE
restart, stop and view active sessions

### PR DESCRIPTION
**Pull request by Jelingam**
this option would help to control over sessions

### CODE REVIEW

**Comment by thebrumby** [comment]
Hi, 

The code you supplied only list the game sessions that are actively making a claim, and not the ones that are sat idle. Is this what you intended?

**Comment by Jelingam** [comment]
hi @thebrumby 
sometimes i want to change something in the games code, for example in seed game.
if i change any part of the code or there is any error in this code, it would restart all seed active sessions and meanwhile if one Seed game want to do claiming process, it will fail because i change original code. these two type restarting repeat and repeat over time, and maybe my account banned for this action.

to prevent this, now i'm stop all seed games manually with`pm2 stop [ID1] [ID2] [ID3] ... `
after stop all seed ID's, i'm start one seed game to see change in code or what happens there.

so if it was some options in `./launch.sh status` like `delete [Pattern]` to stop all seed games, it would be so helpful.
maybe something like `stop [Pattern]`

**Comment by Jelingam** [comment]
and maybe something like `start [Pattern]`  to start all seed ID's after changing in the code

**Comment by thebrumby** [comment]
Hi,

It might get added at some point if we add that functionality to the TG Bot, but for anyone using Linux command line, it's just duplicating the functionality of PM2.

[https://github.com/thebrumby/HotWalletClaimer/issues/137#issuecomment-2241340048](https://github.com/thebrumby/HotWalletClaimer/issues/137#issuecomment-2241340048)

**Comment by Jelingam** [comment]
oh i see
i don't know about this functionality of pm2.
tnx

**Comment by thebrumby** [comment]
Yeah, it's quite helpful. And I added some more functionality to the tg-bot today, so you can also start and stop by pattern there too :)

**Pull request closed without merging**
