### PR TITLE
Claimer Class and Examples

### PR DESCRIPTION
**Pull request by jbr1989**
I created new 'Claimer class' with common code.

I also created 2 examples: Diamond-claimer and Tree-claimer using this class.

I wait for your opinion and if you like it, I will continue to another scripts

### CODE REVIEW

**Comment by thebrumby** [comment]
Wow! 

Great job! If possible, can you give me a few days to wrap my head around all the changes? This definitely looks like the way we should be going, my only concern is that some scripts are setup slightly differently than others, so we might need to incorporate some more settings. 

One example, Blum & Vertus force the proxy on, and maybe another script (that requires the user-agent adding to work well) only enables the proxy if it's set to a user-defined IP, or something like that.

**Comment by jbr1989** [comment]
I have created the class with only common functions.
However, If some script need change any these function, you will be able to override this function in child class.

**Comment by thebrumby** [comment]
I'm loving this method, much better than what I had in mind! I made some changes so far:

Two extra parameters to wether we will force the Proxy (Blum etc), and if we need to force to prompt for a User Agent (Hexacore). Then the user has the option to set a per account user agent if they wish.

I also rewrote a good few of the core functions to improve the moving to elements and clicking etc

As launch_iframe is in the core file, and generally the same for each game (it's the find_link that changes) I deleted it from the game files. 

I'm just doing some final testing and will push it, although Tree looks to be having some issues that will need fixing, but are unrelated to the changes.

**Comment by jbr1989** [comment]
Perfect. Wainting for updates

**Pull request merged**
