### PR TITLE
Profit for hour

### PR DESCRIPTION
**Pull request by jbr1989**
I think the profit for hour is as important as the balance.
For that, I have created new column in status.py for show it, and new log messages.

### CODE REVIEW

**Comment by jbr1989** [comment]
I have created example in seed.py

**Comment by thebrumby** [comment]
Hi JBR, 

Sorry, I've been away from the keyboard for the last week. Let me take a quick look at the changes and I'll approve.

**Comment by thebrumby** [comment]
All working well for me. I'll take a little look at Pixel Tap as it seems to be throwing some errors on the old code too :)

**Comment by thebrumby** [comment]
Hi, 

Just a heads up, but some of the calls of get profit seem to be blocking the game from claiming. If the check for profit involves navigating away from the tab which has the claim stuff on, it needs some way of getting back, or it fails to find the XPATHs:

image

Please don't take it as a criticism, I'm just sharing with you want I found and why I made some small changes. Also, FYI, I'm struggling to get a good way of going back without closing and reopening that pop-up. If you have any ideas, please let me know.

**Comment by jbr1989** [comment]
I think each action needs check your tab and open the tab if it is necessary.

You do the actions in order, but in the future maybe changes and this order also changing. For that, i think is very important the tab en each action.

**Pull request merged**
