### PR TITLE
AutoUpgrades

### PR DESCRIPTION
**Pull request by jbr1989**
Use the base claimer for the autoupgrade claimer.
For example, fuel-autoupgrade is descent of fuel claimer and only overwrite the methods of working different.

Also, the function apply_random_offset is global now

### CODE REVIEW

**Comment by thebrumby** [comment]
Great idea! let me check what the conflict is with `games/lumcity-autoupgrade.py` and I'll adopt it!

**Comment by thebrumby** [comment]
Hi,

I think I correctly merged the updates I made last night which were causing a conflict in the branches. Feel free to double-check if I did it correctly. 

Once again, thanks for all the stuff you are committing to the project!

**Comment by thebrumby** [comment]
Hey, 

It seems none of the auto-upgrade scripts work correctly for setting up new accounts. They seem to be inheriting the script and prefix from the "normal" script and then when starting in PM2, run the normal script not the auto-upgrade version. 

Any suggestions?

**Comment by jbr1989** [comment]
You are right.

The error is use "super().__init__()" in autoupgrade claimer, because the super go to normal claimer.

You can try use "super().super().__init__()". I don't know if work it.

**Comment by thebrumby** [comment]
I think I fixed it :)

**Comment by thebrumby** [comment]
I was going to go down this route:

```
class Claimer():

    def __init__(self):
        self.initialize_settings()
        self.load_settings()
        self.random_offset = random.randint(self.settings['lowestClaimOffset'], self.settings['highestClaimOffset'])
        print(f"Initialising the {self.prefix} Wallet Auto-claim Python Script - Good Luck!")

        self.imported_seedphrase = None

        # Update the settings based on user input
        if len(sys.argv) > 1:
            user_input = sys.argv[1]  # Get session ID from command-line argument
            self.wallet_id = user_input
            self.output(f"Session ID provided: {user_input}", 2)
            
            # Safely check for a second argument
            if len(sys.argv) > 2 and sys.argv[2] == "reset":
                self.settings['forceNewSession'] = True

            # Check for the --seed-phrase flag and validate it
            if '--seed-phrase' in sys.argv:
                seed_index = sys.argv.index('--seed-phrase') + 1
                if seed_index < len(sys.argv):
                    self.seed_phrase = ' '.join(sys.argv[seed_index:])
                    seed_words = self.seed_phrase.split()
                    if len(seed_words) == 12:
                        self.output(f"Seed phrase accepted:", 2)
                        self.imported_seedphrase = self.seed_phrase
                    else:
                        self.output("Invalid seed phrase. Ignoring.", 2)
                else:
                    self.output("No seed phrase provided after --seed-phrase flag. Ignoring.", 2)
        else:
            self.output("\nCurrent settings:", 1)
            for key, value in self.settings.items():
                self.output(f"{key}: {value}", 1)
            user_input = input("\nShould we update our settings? (Default:<enter> / Yes = y): ").strip().lower()
            if user_input == "y":
                self.update_settings()
            user_input = self.get_session_id()
            self.wallet_id = user_input

        self.session_path = "./selenium/{}".format(self.wallet_id)
        os.makedirs(self.session_path, exist_ok=True)
        self.screenshots_path = "./screenshots/{}".format(self.wallet_id)
        os.makedirs(self.screenshots_path, exist_ok=True)
        self.backup_path = "./backups/{}".format(self.wallet_id)
        os.makedirs(self.backup_path, exist_ok=True)
        self.step = "01"

        # Define our base path for debugging screenshots
        self.screenshot_base = os.path.join(self.screenshots_path, "screenshot")

        if self.settings["useProxy"] and self.settings["proxyAddress"] == "http://127.0.0.1:8080":
            self.run_http_proxy()
        elif self.forceLocalProxy:
            self.run_http_proxy()
            self.output("Use of the built-in proxy is force on for this game.", 2)
        else:
            self.output("Proxy disabled in settings.", 2)

    def initialize_settings(self):
        self.settings_file = "variables.txt"
        self.status_file_path = "status.txt"
        self.start_app_xpath = None
        self.settings = {}
        self.driver = None
        self.target_element = None
        self.random_offset = 0
        self.seed_phrase = None
        self.wallet_id = ""
        self.script = "default_script.py"
        self.prefix = "Default:"
   ```
        
  ```
        class FuelClaimer(Claimer):
    
    def initialize_settings(self):
        super().initialize_settings()
        self.script = "games/fuel.py"
        self.prefix = "Fuel:"
        self.url = "https://web.telegram.org/k/#@fueljetton_bot"
        self.pot_full = "Filled"
        self.pot_filling = "to fill"
        self.seed_phrase = None
        self.forceLocalProxy = False
        self.forceRequestUserAgent = True
        self.start_app_xpath = "//span[contains(text(), 'Start pumping oil')]"

    def __init__(self):
        super().__init__()
 ```
        
```
        class FuelAUClaimer(FuelClaimer):
    
    def initialize_settings(self):
        super().initialize_settings()
        self.script = "games/fuel-autoupgrade.py"
        self.prefix = "Fuel-Auto:"

    def __init__(self):
        super().__init__()
        self.start_app_xpath = "//span[contains(text(), 'Start pumping oil')]"
```

But there seems to be stuff not working in quite a few of the games, possibly unrelated to the changes I made, so I'm going to park it for now.

**Comment by thebrumby** [comment]
Hey JBR, 

Sorry, it took such a long time to implement, but I made the changes now. Each auto-upgrade version now pulls the common code from the main game class. 

In the future, I will make a function called auto-upgrade() and put it in the main game class when I want to apply the upgrade, but it will just be a placeholder. Then in the auto-upgrade class, it will just be the one function with the unique inits. 

Thanks for all your contributions.

**Pull request merged**
