### PR TITLE
Telegram bot

### PR DESCRIPTION
**Pull request by jbr1989**
While are configured automatic notifications to telegram, I have created a direct interaction between telegram and "status".

Captura de pantalla 2024-07-04 163430

Now, it is possible obtain the status and logs of one "process", and status of all "processes".
Later, I will add more functions.

What do you think? 

Install dependencies: pip install python-telegram-bot
And define the same "Token_BOT" as the other integration with Telegram

### CODE REVIEW

**Comment by thebrumby** [comment]
Hi,

This looks very promising, or at least a good start. I changed the pip install line to also include requests, which we are using in the claimer file. 

Considering how many none-technical users we seem to have, I'm wondering if it's worth adding this after importing subprocess? After some time and after updating the Docker file, 

```
import subprocess
import sys
try:
from telegram import (ReplyKeyboardMarkup, ReplyKeyboardRemove, Update,
                  InlineKeyboardButton, InlineKeyboardMarkup)
except ImportError:
print("The 'python-telegram-bot' module is not installed. Installing it now...")
subprocess.check_call([sys.executable, "-m", "pip", "install", "python-telegram-bot"])
from telegram import (ReplyKeyboardMarkup, ReplyKeyboardRemove, Update,
                      InlineKeyboardButton, InlineKeyboardMarkup)
```

Also, no doubt you already thought of a solution, but is it worth pulling the token from settings? Something like:

```
def load_telegram_token(file_path: str) -> str:
    """Load the telegram bot token from the specified file."""
    if not os.path.exists(file_path):
        logger.error(f"File {file_path} does not exist.")
        sys.exit(1)

    with open(file_path, 'r') as file:
        lines = file.readlines()
    
    print("File content loaded.")  # Debug print

    for line in lines:
        if 'telegramBotToken' in line:
            print(f"Line found: {line}")  # Debug print
            token = line.split(':')[-1].strip().strip('"')
            if token:
                print(f"Token extracted: {token}")  # Debug print
                return token

    logger.error("telegramBotToken not found in the file.")
    return None
```

```
token = load_telegram_token('variables.txt')
print(f"Token is: {token}")  # Debug print
application = Application.builder().token(token).build()
```

**Comment by thebrumby** [comment]
And just as a question, are you thinking of this instead of the previous one we tried, with output message pushing a message, or as well as?

**Comment by jbr1989** [comment]
1. You can include this code. If it does not cause errors, it looks good.
2. I have also thought to use configuration file. Now, all games use the same file "variables.txt". I think the best is to create a default file "default.txt" and for each game create another file with its own configuration and properties.

**Comment by jbr1989** [comment]
> And just as a question, are you thinking of this instead of the previous one we tried, with output message pushing a message, or as well as?

Both of them:
- One sends you the notifications automatically with the news.
- The other one: If you want more information you can use it.

**Comment by thebrumby** [comment]
Good approach :)

**Comment by thebrumby** [comment]
Hey JBR,

It will probably take some refining over the coming weeks, but I rebuilt the Docker image and pushed the updates. Hopefully I didn't break anything with my changes. The polished instructions can be found here:

https://github.com/thebrumby/HotWalletClaimer/blob/main/docs/TG-BOT.md

Once again, many thanks for contributing this :)

**Pull request merged**
