### PR TITLE
Refactoring Time-farm

### PR DESCRIPTION
**Pull request by jbr1989**

### CODE REVIEW

**Comment by thebrumby** [comment]
Nice! I removed launch_iframe() and just made a couple of tweaks to the get_wait_time function(). Thanks once again :)

**Comment by thebrumby** [comment]
Just a heads up, I'm converting some more of the existing games tonight and testing :)

**Comment by jbr1989** [comment]
Perfect. I am waiting for it.

**Comment by jbr1989** [comment]
Please let me know when you make the conversions, because I'm thinking about further improvements.

**Comment by thebrumby** [comment]
Sure. I already pushed a few ideas about more uniform debugging across move_and_click, monitor_element, etc.

I think the find_working_link can go into the core file and we'll just pass the XPATH as a parameter :) I think it was just seed that has slightly different code right?

**Comment by thebrumby** [comment]
I think it's just Vertus left to move over now, hopefully I can get it done in the next day or so.

I also gave me an opportunity to double-check the operation for the games and make a few improvements :)

**Pull request merged**
